### PR TITLE
fixed inputs padding

### PR DESCRIPTION
**Pull request by razinabrahamyan**

### CODE REVIEW

**Review by alexivanenko — DISMISSED** [review]

**Comment by andrewwhitehead** [comment]
I'm not sure why, but when I test it at the moment I see padding for each density go from 0 (the largest padding) > 2 > 1/default > 3.

**Comment by alexivanenko** [comment]
> I'm not sure why, but when I test it at the moment I see padding for each density go from 0 (the largest padding) > 2 > 1/default > 3.

@andrewwhitehead please check it again, Razin pushed fix

**Comment by andrewwhitehead** [comment]
They seem to be ordered correctly now, but there's a big jump between 0 density and the others. Between 1 and 2, and 2 and 3 it only seems to be a pixel or two difference. Is that intended?

**Comment by alexivanenko** [comment]
@razinabrahamyan what do you think?

**Comment by razinabrahamyan** [comment]
we can increase differences between 1 to 2 and 2 to 3 , and also decrease 0 to 1

**Comment by alexivanenko** [comment]
> we can increase differences between 1 to 2 and 2 to 3 , and also decrease 0 to 1

@razinabrahamyan please do it and we will check

**Review by andrewwhitehead — APPROVED** [review]

**Pull request merged**
